[project]
name = "bara"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.39.0",
    "httpx==0.27.2",
    "python-dotenv>=1.0.1",
    "rich>=13.9.4",
    "scrapybara>=2.0.6",
    "typer>=0.15.1",
]
